---
apiVersion: v1
kind: Service
metadata:
  name: old-webpage-service
  namespace: webpage
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: old-webpage-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: old-webpage
  namespace: webpage
  labels:
    app: old-webpage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: old-webpage-service
  template:
    metadata:
      labels:
        app: old-webpage-service
    spec:
      restartPolicy: Always
      containers:
        - name: server
          image: kamackay/old-webpage:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
---
